// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"context"
	"testing"

	"go.nhat.io/otp"

	mock "github.com/stretchr/testify/mock"
)

// GeneratorMocker is a func that creates a Generator mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type GeneratorMocker func(tb testing.TB) *Generator

// NopGenerator is a Generator mock with no expectation.
var NopGenerator = MockGenerator()

// MockGenerator creates a new Generator mock with cleanup to ensure all the expectations are met.
func MockGenerator(mocks ...func(generator *Generator)) GeneratorMocker {
	return func(tb testing.TB) *Generator {
		tb.Helper()

		generator := NewGenerator(tb)

		for _, configure := range mocks {
			configure(generator)
		}

		return generator
	}
}

// NewGenerator creates a new instance of Generator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Generator {
	mock := &Generator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

type Generator_Expecter struct {
	mock *mock.Mock
}

func (_m *Generator) EXPECT() *Generator_Expecter {
	return &Generator_Expecter{mock: &_m.Mock}
}

// GenerateOTP provides a mock function for the type Generator
func (_mock *Generator) GenerateOTP(ctx context.Context) (otp.OTP, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateOTP")
	}

	var r0 otp.OTP
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (otp.OTP, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) otp.OTP); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(otp.OTP)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Generator_GenerateOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateOTP'
type Generator_GenerateOTP_Call struct {
	*mock.Call
}

// GenerateOTP is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Generator_Expecter) GenerateOTP(ctx any) *Generator_GenerateOTP_Call {
	return &Generator_GenerateOTP_Call{Call: _e.mock.On("GenerateOTP", ctx)}
}

func (_c *Generator_GenerateOTP_Call) Run(run func(ctx context.Context)) *Generator_GenerateOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Generator_GenerateOTP_Call) Return(oTP otp.OTP, err error) *Generator_GenerateOTP_Call {
	_c.Call.Return(oTP, err)
	return _c
}

func (_c *Generator_GenerateOTP_Call) RunAndReturn(run func(ctx context.Context) (otp.OTP, error)) *Generator_GenerateOTP_Call {
	_c.Call.Return(run)
	return _c
}
