// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"context"
	"testing"

	"go.nhat.io/otp"

	mock "github.com/stretchr/testify/mock"
)

// TOTPSecretProviderMocker is a func that creates a TOTPSecretProvider mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type TOTPSecretProviderMocker func(tb testing.TB) *TOTPSecretProvider

// NopTOTPSecretProvider is a TOTPSecretProvider mock with no expectation.
var NopTOTPSecretProvider = MockTOTPSecretProvider()

// MockTOTPSecretProvider creates a new TOTPSecretProvider mock with cleanup to ensure all the expectations are met.
func MockTOTPSecretProvider(mocks ...func(tOTPSecretProvider *TOTPSecretProvider)) TOTPSecretProviderMocker {
	return func(tb testing.TB) *TOTPSecretProvider {
		tb.Helper()

		tOTPSecretProvider := NewTOTPSecretProvider(tb)

		for _, configure := range mocks {
			configure(tOTPSecretProvider)
		}

		return tOTPSecretProvider
	}
}

// NewTOTPSecretProvider creates a new instance of TOTPSecretProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTOTPSecretProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPSecretProvider {
	mock := &TOTPSecretProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TOTPSecretProvider is an autogenerated mock type for the TOTPSecretProvider type
type TOTPSecretProvider struct {
	mock.Mock
}

type TOTPSecretProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TOTPSecretProvider) EXPECT() *TOTPSecretProvider_Expecter {
	return &TOTPSecretProvider_Expecter{mock: &_m.Mock}
}

// DeleteTOTPSecret provides a mock function for the type TOTPSecretProvider
func (_mock *TOTPSecretProvider) DeleteTOTPSecret(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTOTPSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TOTPSecretProvider_DeleteTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTOTPSecret'
type TOTPSecretProvider_DeleteTOTPSecret_Call struct {
	*mock.Call
}

// DeleteTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TOTPSecretProvider_Expecter) DeleteTOTPSecret(ctx any) *TOTPSecretProvider_DeleteTOTPSecret_Call {
	return &TOTPSecretProvider_DeleteTOTPSecret_Call{Call: _e.mock.On("DeleteTOTPSecret", ctx)}
}

func (_c *TOTPSecretProvider_DeleteTOTPSecret_Call) Run(run func(ctx context.Context)) *TOTPSecretProvider_DeleteTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TOTPSecretProvider_DeleteTOTPSecret_Call) Return(err error) *TOTPSecretProvider_DeleteTOTPSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TOTPSecretProvider_DeleteTOTPSecret_Call) RunAndReturn(run func(ctx context.Context) error) *TOTPSecretProvider_DeleteTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}

// SetTOTPSecret provides a mock function for the type TOTPSecretProvider
func (_mock *TOTPSecretProvider) SetTOTPSecret(ctx context.Context, secret otp.TOTPSecret, issuer string) error {
	ret := _mock.Called(ctx, secret, issuer)

	if len(ret) == 0 {
		panic("no return value specified for SetTOTPSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, otp.TOTPSecret, string) error); ok {
		r0 = returnFunc(ctx, secret, issuer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TOTPSecretProvider_SetTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTOTPSecret'
type TOTPSecretProvider_SetTOTPSecret_Call struct {
	*mock.Call
}

// SetTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secret otp.TOTPSecret
//   - issuer string
func (_e *TOTPSecretProvider_Expecter) SetTOTPSecret(ctx any, secret any, issuer any) *TOTPSecretProvider_SetTOTPSecret_Call {
	return &TOTPSecretProvider_SetTOTPSecret_Call{Call: _e.mock.On("SetTOTPSecret", ctx, secret, issuer)}
}

func (_c *TOTPSecretProvider_SetTOTPSecret_Call) Run(run func(ctx context.Context, secret otp.TOTPSecret, issuer string)) *TOTPSecretProvider_SetTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 otp.TOTPSecret
		if args[1] != nil {
			arg1 = args[1].(otp.TOTPSecret)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TOTPSecretProvider_SetTOTPSecret_Call) Return(err error) *TOTPSecretProvider_SetTOTPSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TOTPSecretProvider_SetTOTPSecret_Call) RunAndReturn(run func(ctx context.Context, secret otp.TOTPSecret, issuer string) error) *TOTPSecretProvider_SetTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}

// TOTPSecret provides a mock function for the type TOTPSecretProvider
func (_mock *TOTPSecretProvider) TOTPSecret(ctx context.Context) otp.TOTPSecret {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TOTPSecret")
	}

	var r0 otp.TOTPSecret
	if returnFunc, ok := ret.Get(0).(func(context.Context) otp.TOTPSecret); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(otp.TOTPSecret)
	}
	return r0
}

// TOTPSecretProvider_TOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TOTPSecret'
type TOTPSecretProvider_TOTPSecret_Call struct {
	*mock.Call
}

// TOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TOTPSecretProvider_Expecter) TOTPSecret(ctx any) *TOTPSecretProvider_TOTPSecret_Call {
	return &TOTPSecretProvider_TOTPSecret_Call{Call: _e.mock.On("TOTPSecret", ctx)}
}

func (_c *TOTPSecretProvider_TOTPSecret_Call) Run(run func(ctx context.Context)) *TOTPSecretProvider_TOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TOTPSecretProvider_TOTPSecret_Call) Return(tOTPSecret otp.TOTPSecret) *TOTPSecretProvider_TOTPSecret_Call {
	_c.Call.Return(tOTPSecret)
	return _c
}

func (_c *TOTPSecretProvider_TOTPSecret_Call) RunAndReturn(run func(ctx context.Context) otp.TOTPSecret) *TOTPSecretProvider_TOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
