// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"context"
	"testing"

	mock "github.com/stretchr/testify/mock"
)

// TOTPSecretDeleterMocker is a func that creates a TOTPSecretDeleter mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type TOTPSecretDeleterMocker func(tb testing.TB) *TOTPSecretDeleter

// NopTOTPSecretDeleter is a TOTPSecretDeleter mock with no expectation.
var NopTOTPSecretDeleter = MockTOTPSecretDeleter()

// MockTOTPSecretDeleter creates a new TOTPSecretDeleter mock with cleanup to ensure all the expectations are met.
func MockTOTPSecretDeleter(mocks ...func(tOTPSecretDeleter *TOTPSecretDeleter)) TOTPSecretDeleterMocker {
	return func(tb testing.TB) *TOTPSecretDeleter {
		tb.Helper()

		tOTPSecretDeleter := NewTOTPSecretDeleter(tb)

		for _, configure := range mocks {
			configure(tOTPSecretDeleter)
		}

		return tOTPSecretDeleter
	}
}

// NewTOTPSecretDeleter creates a new instance of TOTPSecretDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTOTPSecretDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPSecretDeleter {
	mock := &TOTPSecretDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TOTPSecretDeleter is an autogenerated mock type for the TOTPSecretDeleter type
type TOTPSecretDeleter struct {
	mock.Mock
}

type TOTPSecretDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *TOTPSecretDeleter) EXPECT() *TOTPSecretDeleter_Expecter {
	return &TOTPSecretDeleter_Expecter{mock: &_m.Mock}
}

// DeleteTOTPSecret provides a mock function for the type TOTPSecretDeleter
func (_mock *TOTPSecretDeleter) DeleteTOTPSecret(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTOTPSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TOTPSecretDeleter_DeleteTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTOTPSecret'
type TOTPSecretDeleter_DeleteTOTPSecret_Call struct {
	*mock.Call
}

// DeleteTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TOTPSecretDeleter_Expecter) DeleteTOTPSecret(ctx any) *TOTPSecretDeleter_DeleteTOTPSecret_Call {
	return &TOTPSecretDeleter_DeleteTOTPSecret_Call{Call: _e.mock.On("DeleteTOTPSecret", ctx)}
}

func (_c *TOTPSecretDeleter_DeleteTOTPSecret_Call) Run(run func(ctx context.Context)) *TOTPSecretDeleter_DeleteTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TOTPSecretDeleter_DeleteTOTPSecret_Call) Return(err error) *TOTPSecretDeleter_DeleteTOTPSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TOTPSecretDeleter_DeleteTOTPSecret_Call) RunAndReturn(run func(ctx context.Context) error) *TOTPSecretDeleter_DeleteTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
