// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"context"
	"testing"

	"go.nhat.io/otp"

	mock "github.com/stretchr/testify/mock"
)

// TOTPSecretSetterMocker is a func that creates a TOTPSecretSetter mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type TOTPSecretSetterMocker func(tb testing.TB) *TOTPSecretSetter

// NopTOTPSecretSetter is a TOTPSecretSetter mock with no expectation.
var NopTOTPSecretSetter = MockTOTPSecretSetter()

// MockTOTPSecretSetter creates a new TOTPSecretSetter mock with cleanup to ensure all the expectations are met.
func MockTOTPSecretSetter(mocks ...func(tOTPSecretSetter *TOTPSecretSetter)) TOTPSecretSetterMocker {
	return func(tb testing.TB) *TOTPSecretSetter {
		tb.Helper()

		tOTPSecretSetter := NewTOTPSecretSetter(tb)

		for _, configure := range mocks {
			configure(tOTPSecretSetter)
		}

		return tOTPSecretSetter
	}
}

// NewTOTPSecretSetter creates a new instance of TOTPSecretSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTOTPSecretSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPSecretSetter {
	mock := &TOTPSecretSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TOTPSecretSetter is an autogenerated mock type for the TOTPSecretSetter type
type TOTPSecretSetter struct {
	mock.Mock
}

type TOTPSecretSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *TOTPSecretSetter) EXPECT() *TOTPSecretSetter_Expecter {
	return &TOTPSecretSetter_Expecter{mock: &_m.Mock}
}

// SetTOTPSecret provides a mock function for the type TOTPSecretSetter
func (_mock *TOTPSecretSetter) SetTOTPSecret(ctx context.Context, secret otp.TOTPSecret, issuer string) error {
	ret := _mock.Called(ctx, secret, issuer)

	if len(ret) == 0 {
		panic("no return value specified for SetTOTPSecret")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, otp.TOTPSecret, string) error); ok {
		r0 = returnFunc(ctx, secret, issuer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TOTPSecretSetter_SetTOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTOTPSecret'
type TOTPSecretSetter_SetTOTPSecret_Call struct {
	*mock.Call
}

// SetTOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secret otp.TOTPSecret
//   - issuer string
func (_e *TOTPSecretSetter_Expecter) SetTOTPSecret(ctx any, secret any, issuer any) *TOTPSecretSetter_SetTOTPSecret_Call {
	return &TOTPSecretSetter_SetTOTPSecret_Call{Call: _e.mock.On("SetTOTPSecret", ctx, secret, issuer)}
}

func (_c *TOTPSecretSetter_SetTOTPSecret_Call) Run(run func(ctx context.Context, secret otp.TOTPSecret, issuer string)) *TOTPSecretSetter_SetTOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 otp.TOTPSecret
		if args[1] != nil {
			arg1 = args[1].(otp.TOTPSecret)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TOTPSecretSetter_SetTOTPSecret_Call) Return(err error) *TOTPSecretSetter_SetTOTPSecret_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TOTPSecretSetter_SetTOTPSecret_Call) RunAndReturn(run func(ctx context.Context, secret otp.TOTPSecret, issuer string) error) *TOTPSecretSetter_SetTOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
