// Code generated by mockery v2.53.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	otp "go.nhat.io/otp"
)

// TOTPSecretSetter is an autogenerated mock type for the TOTPSecretSetter type
type TOTPSecretSetter struct {
	mock.Mock
}

// SetTOTPSecret provides a mock function with given fields: ctx, secret, issuer
func (_m *TOTPSecretSetter) SetTOTPSecret(ctx context.Context, secret otp.TOTPSecret, issuer string) error {
	ret := _m.Called(ctx, secret, issuer)

	if len(ret) == 0 {
		panic("no return value specified for SetTOTPSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, otp.TOTPSecret, string) error); ok {
		r0 = rf(ctx, secret, issuer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTOTPSecretSetter creates a new instance of TOTPSecretSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTOTPSecretSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPSecretSetter {
	mock := &TOTPSecretSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
