// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: https://github.com/nhatthm/mockery-template

package mock

import (
	"context"
	"testing"

	"go.nhat.io/otp"

	mock "github.com/stretchr/testify/mock"
)

// TOTPSecretGetterMocker is a func that creates a TOTPSecretGetter mock. It is used to compose
// mock expectations from other packages without exposing *testing.T.
type TOTPSecretGetterMocker func(tb testing.TB) *TOTPSecretGetter

// NopTOTPSecretGetter is a TOTPSecretGetter mock with no expectation.
var NopTOTPSecretGetter = MockTOTPSecretGetter()

// MockTOTPSecretGetter creates a new TOTPSecretGetter mock with cleanup to ensure all the expectations are met.
func MockTOTPSecretGetter(mocks ...func(tOTPSecretGetter *TOTPSecretGetter)) TOTPSecretGetterMocker {
	return func(tb testing.TB) *TOTPSecretGetter {
		tb.Helper()

		tOTPSecretGetter := NewTOTPSecretGetter(tb)

		for _, configure := range mocks {
			configure(tOTPSecretGetter)
		}

		return tOTPSecretGetter
	}
}

// NewTOTPSecretGetter creates a new instance of TOTPSecretGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTOTPSecretGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TOTPSecretGetter {
	mock := &TOTPSecretGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TOTPSecretGetter is an autogenerated mock type for the TOTPSecretGetter type
type TOTPSecretGetter struct {
	mock.Mock
}

type TOTPSecretGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *TOTPSecretGetter) EXPECT() *TOTPSecretGetter_Expecter {
	return &TOTPSecretGetter_Expecter{mock: &_m.Mock}
}

// TOTPSecret provides a mock function for the type TOTPSecretGetter
func (_mock *TOTPSecretGetter) TOTPSecret(ctx context.Context) otp.TOTPSecret {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TOTPSecret")
	}

	var r0 otp.TOTPSecret
	if returnFunc, ok := ret.Get(0).(func(context.Context) otp.TOTPSecret); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(otp.TOTPSecret)
	}
	return r0
}

// TOTPSecretGetter_TOTPSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TOTPSecret'
type TOTPSecretGetter_TOTPSecret_Call struct {
	*mock.Call
}

// TOTPSecret is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TOTPSecretGetter_Expecter) TOTPSecret(ctx any) *TOTPSecretGetter_TOTPSecret_Call {
	return &TOTPSecretGetter_TOTPSecret_Call{Call: _e.mock.On("TOTPSecret", ctx)}
}

func (_c *TOTPSecretGetter_TOTPSecret_Call) Run(run func(ctx context.Context)) *TOTPSecretGetter_TOTPSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TOTPSecretGetter_TOTPSecret_Call) Return(tOTPSecret otp.TOTPSecret) *TOTPSecretGetter_TOTPSecret_Call {
	_c.Call.Return(tOTPSecret)
	return _c
}

func (_c *TOTPSecretGetter_TOTPSecret_Call) RunAndReturn(run func(ctx context.Context) otp.TOTPSecret) *TOTPSecretGetter_TOTPSecret_Call {
	_c.Call.Return(run)
	return _c
}
