dir: '{{.InterfaceDir}}/mock'
structname: '{{.InterfaceName}}'
filename: "{{ .InterfaceName | snakecase }}.go"
pkgname: mock
template: "https://raw.githubusercontent.com/nhatthm/mockery-template/0.3.0/templates/testify-mocker.templ"
template-data:
  unroll-variadic: true
packages:
  go.nhat.io/otp:
    config:
      exclude-interface-regex: Option|.+(Func|Option)
      include-interface-regex: .+
